development:
  enabled: true
  inspector: 'all'
  # what language to support and their display names
  lang:
    en: 'English'
    de: 'Deutsch'
    ar: 'عربى'
    cz: 'český'
    fr: 'français'
    es: 'español'
  yaml_translator_email: 'admin@me.com'
  i18n_source: 'db' # can be db or yaml; default is yaml
  yaml2db_translations_accepted: true # when import translation from yaml to db set it to accepted by default; default is false
  accept_admin_translations: true # when admins add/edit translations they are considered accepted directly
  save_default_translation: true # when a new key is added to db, the value of the key is added as the default translation in English
production:
  enabled: true
  inspector: 'missing'
  # what language to support and their display names
  lang:
    en: 'English'
    de: 'Deutsch'
    ar: 'عربى'
    cz: 'český'
    fr: 'français'
    es: 'español'
  yaml_translator_email: 'admin@me.com'
  i18n_source: 'yaml' # can be db or yaml; default is yaml
  yaml2db_translations_accepted: true # when import translation from yaml to db set it to accepted by default; default is false
  accept_admin_translations: true # when admins add/edit translations they are considered accepted directly
  save_default_translation: true # when a new key is added to db, the value of the key is added as the default translation in English
